// Collects every non-ASCII character used in the film's source (content,
// components, and the product cover generator) so fonts.ts loads only the
// Noto Sans/Serif SC unicode slices that are actually needed.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const roots = [join(__dirname, "../src"), join(__dirname, "../../web/lib/cover"), join(__dirname, "../../web/lib/stations.ts")];
const chars = new Set<string>();
function walk(path: string) {
  if (statSync(path).isDirectory()) {
    for (const name of readdirSync(path)) if (!name.includes("generated")) walk(join(path, name));
    return;
  }
  if (!/\.(ts|tsx)$/.test(path)) return;
  for (const ch of readFileSync(path, "utf8")) if (ch.codePointAt(0)! > 0x7f) chars.add(ch);
}
roots.forEach(walk);
const text = [...chars].sort().join("");
writeFileSync(join(__dirname, "../src/charset.generated.ts"), `// Generated by scripts/build-charset.ts. Do not edit.\nexport const CHARSET = ${JSON.stringify(text)};\n`);
console.log(`charset: ${chars.size} characters`);
